### PR TITLE
Added maxBuffer option (10MB)

### PR DESCRIPTION
**Pull request by elwerene**

### CODE REVIEW

**Comment by hurrymaplelad** [comment]
Good stuff.  Mind making buffer size configurable?  Also makes me wonder if we should expose a streaming API using [`spawn`](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options), and make buffering opt-in.

**Comment by elwerene** [comment]
made it configurable :)

**Comment by hurrymaplelad** [comment]
Thanks!  How 'bout a test to make sure I don't break it later?

**Comment by hurrymaplelad** [comment]
LGTM, thanks @elwerene! I'll add a quick test.

**Comment by hurrymaplelad** [comment]
Published as `v1.0.0`

**Pull request merged**
